# Generated by Django 3.2.9 on 2021-12-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hearingLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='account',
            name='signType',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='userType',
            field=models.IntegerField(default=1),
        ),
    ]
