# Generated by Django 3.2.9 on 2021-12-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handiApp', '0002_auto_20211214_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
