# Generated by Django 3.2.9 on 2021-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handiApp', '0004_populate_bd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hearingLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='signType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='userType',
            field=models.IntegerField(default=0),
        ),
    ]
